spring.application.name=glassabbey-backend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/glassabbey
spring.datasource.username=postgres
spring.datasource.password=pass

# JPA
# Show or not log for each sql query
spring.jpa.show-sql=true

# Hibernate ddl auto (create, create-drop, update): with "update" the database
spring.jpa.hibernate.ddl-auto=validate

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.format_sql=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#jwt
jwt.secret=7qXkWQWNrxAtmvbdBSYg/5EPR2/WraIlUvV/FteVPSA=
jwt.expiration=604800000

#
auction.submission-fee-sats=${AUCTION_SUBMISSION_FEE_SATS:100}

# generate with: openssl rand -hex 32
nwc.encryption.key=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

